version: '3.7'

services:
  api:
    build: .
    container_name: mitrixgpt-chatserver
    env_file:
      - .env
    ports:
      - '3000:3000'
    restart: "always"
  qdrant:
    image: qdrant/qdrant:latest
    ports:
      - "6333:6333"
      - "6334:6334"
    volumes:
      - ./storage/volumes/qdrant_data:/qdrant/storage:z
  postgres:
    image: postgres:15
    container_name: postgres
    restart: always
    ports:
      - "5433:5432"
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: mitrixgpt
    volumes:
      - ./storage/volumes/postgres_data:/var/lib/postgresql/data
