apiVersion: v1
kind: Service
metadata:
  name: {{ include "mitrixgpt-agent.fullname" . }}
  labels:
    {{- include "mitrixgpt-agent.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: 3000
      targetPort: 3000
      protocol: TCP
  selector:
    {{- include "mitrixgpt-agent.selectorLabels" . | nindent 4 }}
