apiVersion: v1
kind: Service
metadata:
  name: {{ include "mitrixgpt-agent.fullname" . }}
  annotations:
    cloud.google.com/load-balancer-type: "External"  # Use "Internal" for ILB
    cloud.google.com/neg: '{"exposed_ports": {"80":{"name": "agent-mitrixgpt-agent-neg"}}}'  # Enables NEGs
    cloud.google.com/healthcheck-path: "/-/healthz"
    cloud.google.com/healthcheck-timeout-seconds: "10"
    cloud.google.com/healthcheck-interval-seconds: "10"
    cloud.google.com/healthcheck-unhealthy-threshold: "3"
    cloud.google.com/healthcheck-healthy-threshold: "2"
  labels:
    {{- include "mitrixgpt-agent.labels" . | nindent 4 }}
spec:
  # type: {{ .Values.service.type }}
  type: LoadBalancer
  externalTrafficPolicy: Local
  ports:
    - port: 3000
      targetPort: 3000
      protocol: TCP
  selector:
    {{- include "mitrixgpt-agent.selectorLabels" . | nindent 4 }}
